name: Despliegue_Android

on:
  push:
    tags:
      - "v*"      # Solo se activará la acción cuando se suba un tag que comience por 'v'
permissions:
  actions: write
  contents: write
jobs:
 build_android:
   runs-on: ubuntu-latest

   steps:
    - name: Clonado del repositorio                         # Clonado del repositorio
      uses: actions/checkout@v4
    - name: Instalación de Java                             # Instalación de Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Instalación de Flutter                          # Instalación de flutter
      uses: subosito/flutter-action@v4
      with:
        channel: 'stable'
    - name: Instalación de dependencias del proyecto        # Dependencias del proyecto
      run: flutter pub get
    - name: Compilación y creación del AAB                  # AAB
      run: flutter build appbundle --release
    - name: Compilación y creación del APK                  # APK
      run: flutter build apk --release --split-per-abi
    - name: Publicación en GitHub Releases                  # GitHub Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        github_token: "${{ secrets.WORKFLOW1_TOKEN }}"
        prerelease: false
        files: |                                            # Archivos que se subirán
          build/app/outputs/bundle/release/app-release.aab
          build/app/outputs/apk/release/*.apk
